services:
    app:
        command:
            [
                "hypercorn",
                "--worker-class={{ cookiecutter.worker_class }}",
                "--bind=0.0.0.0:5000",
                "--error-logfile=-",
                "--reload",
                "--root-path=/api",
                "{{cookiecutter.project_slug}}.main:app"
            ]
        volumes:
            - ./{{cookiecutter.project_slug}}/:/app/{{cookiecutter.project_slug}}/
        environment:
            - ENV=development
