services:

    caddy:
        # see https://hub.docker.com/_/caddy
        image: caddy:alpine
        container_name: caddy
        init: true
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
        depends_on:
            - app
        restart: unless-stopped
        environment:
            - DOMAIN

    app:
        image: {{cookiecutter.project_slug}}
        container_name: {{cookiecutter.project_slug}}
        build: .
        init: true
        ports:
            - "5000:5000"
        restart: unless-stopped
        env_file:
            - .env
        environment:
            ENV: ${ENV:-production}
        command:
            [
                "hypercorn",
                "--config=hypercorn.toml",
                "--root-path=/api",
                "{{cookiecutter.project_slug}}.main:app"
            ]

volumes:
    caddy_data:
