services:

    caddy:
        # see https://hub.docker.com/_/caddy
        image: caddy:alpine
        container_name: caddy
        init: true
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
        depends_on:
            - app
        restart: unless-stopped
        environment:
            - DOMAIN

    db:
        container_name: db
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        restart: unless-stopped

    app:
        image: {{cookiecutter.project_slug}}
        container_name: {{cookiecutter.project_slug}}
        build: .
        init: true
        ports:
            - "5000:5000"
        restart: unless-stopped
        depends_on:
            - db
        env_file:
            - .env
        environment:
            DB_HOST: db
            ENV: ${ENV:-production}

volumes:
    caddy_data:
