version: "3.9"

networks:
    web:
        driver: bridge
    backend:
        driver: bridge
        internal: true

services:
    caddy:
        # see https://hub.docker.com/_/caddy
        image: caddy:alpine
        container_name: caddy
        init: true
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
        networks:
            - web
            - backend
        depends_on:
            - app
        restart: unless-stopped

    app:
        image: {{cookiecutter.project_slug}}:latest
        container_name: {{cookiecutter.project_slug}}
        build: .
        init: true
        ports:
            - "5000:5000"
        networks:
            - backend
        restart: unless-stopped
        environment:
            ENV: ${ENV:-production}

volumes:
    caddy_data:
