[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = ""
authors = ["{{cookiecutter.author}} <{{cookiecutter.email}}>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^{{cookiecutter.python_version}}"
fastapi = "*"
hypercorn = "*"
loguru = "*"
orjson = "*"
uvloop = "*"

[tool.poetry.dev-dependencies]
asgi-lifespan = "*"
alt-pytest-asyncio = "*"
blue = "0.5.2"
bandit = "*"
flake8 = "*"
flake8-debugger = "*"
flake8-pytest-style = "*"
httpx = "*"
isort = "*"
mypy = "*"
pep8-naming = "*"
pip-audit = "*"
pytest = "*"
pytest-cov = "*"
pyupgrade = "*"

[tool.isort]
profile = "black"
line_length = {{cookiecutter.line_length}}

[tool.blue]
line-length = {{cookiecutter.line_length}}

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
