[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = ""
authors = ["{{cookiecutter.author}} <{{cookiecutter.email}}>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
asyncpg = "*"
databases = "*"
email_validator = "*"
fastapi = "*"
hypercorn = "*"
loguru = "*"
orjson = "*"
passlib = { extras = ["argon2"], version = "*" }
psycopg2 = "*"
python = "^{{cookiecutter.python_version}}"
python-dotenv = "*"
tenacity = "*"
uvloop = "*"

[tool.poetry.dev-dependencies]
asgi-lifespan = "*"
alt-pytest-asyncio = "*"
bandit = "*"
blue = "*"
Faker = "*"
httpx = "*"
isort = "*"
mypy = "*"
pip-audit = "*"
pytest = "*"
pytest-cov = "*"
pyupgrade = "*"
ruff = "*"

[tool.isort]
profile = "black"
line_length = {{cookiecutter.line_length}}

[tool.blue]
line-length = {{cookiecutter.line_length}}

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.ruff]
line-length = {{cookiecutter.line_length}}
select = ["A", "B", "C", "E", "F", "N", "T", "U"]
per-file-ignores = { "__init__.py" = ["F401"] }
target-version = "py{{cookiecutter.python_version.replace('.', '')}}"
