name: Test Template Instantiation

on: [push]

jobs:

  lint_and_test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:

        - name: Set up python
          uses: actions/setup-python@v4
          with:
              python-version: '3.11'

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Test
          run: make test
